In [79]:
import numpy as np 
import sympy as sp

In [4]:
# manual convolution implementation for a 1D array 

In [86]:
a = np.array([1, 2, 1])
b = np.array([1, 3, 4, 6, 1, 1, 3]) # the input needs to be flipped!

# without padding 
def convolution(a, b):
    dot_product = []
    b = np.flip(b)
    for i in range(1, len(b)-1):
        dot_product.append(sum(a * b[i-1:i+2]))
    return np.array(dot_product)
    
# circular padding
def circular_convolution(a, b):
    out = []
    b = np.flip(b)
    for i in range(len(b)):
        if i >= len(b)-1:
            i -= len(b)
        d = 0
        for j in range(len(a)):
            d += a[j] * b[i-1+j]
        out.append(d)
    return np.array(out)

In [72]:
convolution(a, b)
circular_convolution(a, b)

array([ 8,  6,  9, 17, 17, 11,  8])

In [59]:
np.convolve(a, b, mode='valid')
np.convolve(a, b, mode='full') # pads with 0 

array([ 1,  5, 11, 17, 17,  9,  6,  7,  3])

In [60]:
### numpy does not natively flip the input. 

In [ ]:
# Properties of convolution 

In [91]:
### commutative f*g = g*f
np.convolve(a, b, mode='valid') == np.convolve(b, a, mode='valid')

### integrals of convolution: The integral of a convolution is the multiplication of integrals
discrete_integral = sum(a) + sum(b)
discrete_integral == sum(np.concatenate((a, b)))

### impulse response
b_1 = np.array(1)
np.convolve(b_1, a, mode='valid') == a

array([ True,  True,  True])

In [ ]:
# "Convolution in the time domain is multiplication in the frequency (Fourier) domain."